CREATE TABLE TRADE(
   ID SERIAL PRIMARY KEY,
   ORDERREF INTEGER,
   ORDERPAIR INTEGER,
   PAIR VARCHAR(8),
   TYPE CHAR(4),
   PRICE MONEY,
   QTY decimal(10,5),
   TXNDATE TIMESTAMP,
   STATUS VARCHAR(6),
   orderId BigInt,
   clientOrderId VarChar(20),
   priceRes money,
  origQty VarChar(10),
  executedQty VarChar(10),
  cummulativeQuoteQty VarChar(15),
  statusRes VarChar(10),
  timeInForce VarChar(6),
  typeRes VarChar(8),
  sideRes VarChar(5),
  stopPrice VarChar(10),
  icebergQty Varchar(10),
  timeRes BigInt,
  updateTime BigInt,
  isWorking Boolean,
  accountId Integer,
  isIsolated Boolean

);
